POST http://localhost:8082/orders
Content-Type: application/json

{
  "customerName": "haitam modli",
  "customerEmail": "haitam@gmail.com",
  "items": [
    {
      "productId": 2,
      "quantity": 8
    }
  ]
}
